# Note: DB use decommissioned for demo deployment. Reenable if restoring db use.
# databases:
#   - name: subvixen
#     databaseName: subvixen
#     user: subvixen
# plan: free

services:
  - type: web
    name: subvixen
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: 'bundle exec rails server'
    envVars:
      # Note: DB use decommissioned for demo deployment. Reenable if restoring db use.
      # - key: DATABASE_URL
      # fromDatabase:
      # name: subvixen
      # property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
